### ISSUE TITLE
cannot start RIse

### ISSUE THREAD

**Issue by neilhuang007** [MatrixAura/Rise#1]
```
Exception in thread "Client thread" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:843)
	at java.lang.System.loadLibrary(System.java:1136)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:2452)
	at net.minecraft.util.Timer.<init>(Timer.java:56)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:170)
	at net.minecraft.client.main.Main.main(Main.java:101)
	at Start.main(Start.java:8)
```

please fix this

**Comment by MatrixAura** [comment]
加上jvm参数 -Djava.library.path=""
引号是native路径
下载1.8.9并把1.8.9-native文件夹路径复制到引号里
